dist: trusty
sudo: false
addons:
  postgresql: 9.6

language: elixir
elixir: 1.7.4

cache:
  directories:
    - deps
    - _build
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
